Fix for:
fatal error: /usr/bin/codesign_allocate: can't allocate code signature data
for _core.cpython-39-darwin.so (for architecture x86_64) because larger
updated load commands do not fit (the program must be relinked using a
larger -headerpad value)